// var openers = [
//   'is about to go Loconut',
//   'is feeling fine and dandy like sour candy',
//   'just smacked everyone\'s butt with a yard o\' beef',
//   'is definitely not the Tangerine Bandit',
//   'might secretly enjoy Lifehouse',
//   'is fat-cattin\' all day, every day',
//   'has lunchspiration problems',
//   'can\'t spin a leek for beans',
//   'doesn\'t have anything to hide, but still wears shorts in the shower anyway',
//   'both smelt it and delt it',
//   'just developed irritable bowel syndrome',
//   'was spotted drinking appletinis at the bowling alley bar',
//   'ate too much kringle today',
//   'needs a sabbatical',
//   'pickles their own cucumbers and never shuts up about it',
//   'needs to feed Sophie her cold cuts for the day',
//   'is finally going to buy those Phillips Smartbulbs after all',
//   'can cook minute rice in 55 seconds',
//   'got fired from the M&Ms factory for throwing away all the W\'s',
//   'can kill two stones with one bird',
//   'still uses Ask Jeeves',
//   'volunteered to dev a one page checkout',
//   'was the one who forgot the beer when we went tubing',
//   'has already scheduled a Halloween party for October 2019',
//   'is not really allowed to play but we\'re trying to be inclusive here',
//   'is a major player down at the cracker factory',
//   'puts the "laughter" in "manslaughter"',
//   'drinks the bag of bacon juice when no one\'s looking',
//   'is wondering when to start that pooper scooper business',
//   'got the Klondike bar but now lives in constant regret',
//   'is the reason why we can\'t have hummus anymore',
//   'thinks we\'re all a bunch of Eurotrash',
//   'ate all the skins off the fried chicken and then just left',
//   'only comes to work for the beef jerky',
//   'insists that we use their adult film name',
//   'is getting a little too good at bar games',
//   'is buying the winner a Bud Light Orange',
//   'is being forced to sew gold jackets',
//   'is on probation for Googling',
//   'is totally not playing on a client call',
//   'is wearing a bathrobe stolen from the Knight\'s Inn',
//   'doesn\'t wear pants when WFH',
// ];


var openers = [
  'is trapped in R. Kelly\'s closet',
  'is suspiciously never seen during the day and is allergic to garlic',
  'is hosting a BYOB seance later tonight',
  'was bobbing for apples but bit something that wasn\'t an apple',
  'put some unsavory things in the Halloween feel box',
  'is always the one moving the ouija board',
  'put a hex on the research department',
  'egged the parking lot security guard',
  'is being a dick and giving children toothbrushes for treats this year',
  'is demanding "tricks" instead of treats from visitors and it\'s weird',
  'still has nightmares about deving that one page checkout',
  'toilet papered Home Away\'s office',
  'is A/B testing which blood type tastes better',
  'wasn\'t boiling their water all week',
  'wonders why their hair only grows out during a full moon',
  'needs to wrap this up and get back to exorcisms',
  'is WFGraveyard',
  'keeps doing the Thriller dance and it has to stop',
  'is buying their kid a lovely doll named "Chucky" on AG',
  'is refusing to put the lotion in the basket',
  'wants BRAAAIINS but will settle for expired lunchmeat',
  'didn\'t realize just how much rum was in the hot apple cider',
  'got lost on the ghost tour and we\'re not going to backtrack now',
  'blatantly took more than one candy bar from the bowl',
  'keeps inviting us to their "escape room" but we know better',
  'better not get any circus peanuts this year...',
  'could afford to give everyone a king sized candy bar... Fatcat',
  'deactivated all the electronic door locks and wants to "play a game"',
  'prepicked cheap pumpkins at Walmart and swapped them at the patch behind their kid\'s backs',
  'fell into a 5-year sugar coma',
  'is serving some strange-tasting meat at their Halloween party',
  'has been listening to a little too much Rob Zombie lately',
  'spiked the vampire\'s blood punch with Loconut (the bad melon kind)',
  'is dressing up as a sexy DDR this year',
  'didn\'t get ghoulie and now has to get out',
  'is dressing up as :paden: for halloween',
  'is butt naked, howling at the moon',
  'is handing out candy to children from the back of their van',
  'is changing their pants after seeing a :ghost:',
  'just saw a black cat but wished it was a :fat-cat:',
  'crossed the road to get to the other Hyde',
  'is just here for the boos',
  'is "something about kissing a vampire and it being a pain in the neck" -Cara',
];


module.exports = openers;






