var openers = [
  'is illegally building a wall of lego bricks around the office',
  'bites right into string cheese without peeling it like a serial killer',
  'forgot to wear red flannel today and feels very left out',
  'actually pays someone to deliver gas to their car',
  'is afraid to eat baby carrots because of the bleach,',
  'is cutting back and can only afford 4 fishing trips to the Bahamas this year',
  'made "stew" for lunch and really wants us to try it for some reason',
  'was caught deflating kickballs in the locker room',
  'passed gas and blamed it on Knox',
  'intentionally spilled a bag of Chex Mix on the plane and told the stewardess to "deal with it"',
  'is playing with wood',
  'eats yogurt with a fork like a freak',
  'has to go home early today for yet another TV delivery',
  'is getting sneaky-married this weekend',
  'was kicked out of the Superbowl for shining a laser pointer in Tom Brady\'s eye',
  'drank a margarita out of a coffee cup this morning',
  'sends pointless late night emails just to impress coworkers',
  'keeps bringing their karaoke machine despite no one asking for it',
  'only showers in Fiji water',
  'will be hosting a Ted Talk on manure later',
  'is still recovering financially from investing in all that Ripple',
  'secretly enabled \'Touch up my appearance\' in Zoom',
  'was featured on Optimizely\'s homepage for 2 months and no one even noticed',
  'is wondering when it\'s going to be Pretzel Day again',
  'is dying to be invited to #frequent-urinators',
  'has got to stop smacking people with a wet tuna',
  'will not stop asking us to buy their Lexus',
  'got fired from the calendar factory for taking a day off',
  'keeps uninstalling Fire Fox from everyone\'s computer',
  'posted an unflattering toilet paper selfie and is ostracized from the CH community',
  'still listens to Limp Bizkit',
  'is too full of fried chicken to do any more work today',
  'is considering a face tattoo to look more millenial',
  'woke up this morning covered in Flaming Hot Cheeto crumbs',
  'has had it with Home Away camping in our toilets',
  'nearly collapsed from working until 3pm yesterday',
  'lied to everyone and said they were WFCosmic but really just hung out and drank beer',
  'was caught shopping online at work but claimed it was for QA',
  'still connects to the Internet using AOL free trial CDs',
  'honestly puts more effort into their Simms character than this job',
];

  // 'is about to go Loconut',
  // 'is feeling fine and dandy like sour candy',
  // 'just smacked everyone\'s butt with a yard o\' beef',
  // 'is definitely not the Tangerine Bandit',
  // 'might secretly enjoy Lifehouse',
  // 'is fat-cattin\' all day, every day',
  // 'has lunchspiration problems',
  // 'can\'t spin a leek for beans',
  // 'doesn\'t have anything to hide, but still wears shorts in the shower anyway',
  // 'both smelt it and delt it',
  // 'just developed irritable bowel syndrome',
  // 'was spotted drinking appletinis at the bowling alley bar',
  // 'ate too much kringle today',
  // 'needs a sabbatical',
  // 'pickles their own cucumbers and never shuts up about it',
  // 'needs to feed Sophie her cold cuts for the day',
  // 'is finally going to buy those Phillips Smartbulbs after all',
  // 'can cook minute rice in 55 seconds',
  // 'got fired from the M&Ms factory for throwing away all the W\'s',
  // 'can kill two stones with one bird',
  // 'still uses Ask Jeeves',
  // 'volunteered to dev a one page checkout',
  // 'was the one who forgot the beer when we went tubing',
  // 'has already scheduled a Halloween party for October 2019',
  // 'is not really allowed to play but we\'re trying to be inclusive here',
  // 'is a major player down at the cracker factory',
  // 'puts the "laughter" in "manslaughter"',
  // 'drinks the bag of bacon juice when no one\'s looking',
  // 'is wondering when to start that pooper scooper business',
  // 'got the Klondike bar but now lives in constant regret',
  // 'is the reason why we can\'t have hummus anymore',
  // 'thinks we\'re all a bunch of Eurotrash',
  // 'ate all the skins off the fried chicken and then just left',
  // 'only comes to work for the beef jerky',
  // 'insists that we use their adult film name',
  // 'is getting a little too good at bar games',
  // 'is buying the winner a Bud Light Orange',
  // 'is being forced to sew gold jackets',
  // 'is on probation for Googling',
  // 'is totally not playing on a client call',
  // 'is wearing a bathrobe stolen from the Knight\'s Inn',
  // 'doesn\'t wear pants when WFH',


// var openers = [
//   'is trapped in R. Kelly\'s closet',
//   'is suspiciously never seen during the day and is allergic to garlic',
//   'is hosting a BYOB seance later tonight',
//   'was bobbing for apples but bit something that wasn\'t an apple',
//   'put some unsavory things in the Halloween feel box',
//   'is always the one moving the ouija board',
//   'put a hex on the research department',
//   'egged the parking lot security guard',
//   'is being a dick and giving children toothbrushes for treats this year',
//   'is demanding "tricks" instead of treats from visitors and it\'s weird',
//   'still has nightmares about deving that one page checkout',
//   'toilet papered Home Away\'s office',
//   'is A/B testing which blood type tastes better',
//   'wasn\'t boiling their water all week',
//   'wonders why their hair only grows out during a full moon',
//   'needs to wrap this up and get back to exorcisms',
//   'is WFGraveyard',
//   'keeps doing the Thriller dance and it has to stop',
//   'is buying their kid a lovely doll named "Chucky" on AG',
//   'is refusing to put the lotion in the basket',
//   'wants BRAAAIINS but will settle for expired lunchmeat',
//   'didn\'t realize just how much rum was in the hot apple cider',
//   'got lost on the ghost tour and we\'re not going to backtrack now',
//   'blatantly took more than one candy bar from the bowl',
//   'keeps inviting us to their "escape room" but we know better',
//   'better not get any circus peanuts this year...',
//   'could afford to give everyone a king sized candy bar... Fatcat',
//   'deactivated all the electronic door locks and wants to "play a game"',
//   'prepicked cheap pumpkins at Walmart and swapped them at the patch behind their kid\'s backs',
//   'fell into a 5-year sugar coma',
//   'is serving some strange-tasting meat at their Halloween party',
//   'has been listening to a little too much Rob Zombie lately',
//   'spiked the vampire\'s blood punch with Loconut (the bad melon kind)',
//   'is dressing up as a sexy DDR this year',
//   'didn\'t get ghoulie and now has to get out',
//   'is dressing up as :paden: for halloween',
//   'is butt naked, howling at the moon',
//   'is handing out candy to children from the back of their van',
//   'is changing their pants after seeing a :ghost:',
//   'just saw a black cat but wished it was a :fat-cat:',
//   'crossed the road to get to the other Hyde',
//   'is just here for the boos',
//   'is "something about kissing a vampire and it being a pain in the neck" -Cara',
// ];


module.exports = openers;






