var openers = [
  'is about to go Loconut',
  'is feeling fine and dandy like sour candy',
  'just smacked everyone\'s butt with a yard o\' beef',
  'is definitely not the Tangerine Bandit',
  'might secretly enjoy Lifehouse',
  'is fat-cattin\' all day, every day',
  'has lunchspiration problems',
  'can\'t spin a leek for beans',
  'doesn\'t have anything to hide, but still wears shorts in the shower anyway',
  'both smelt it and delt it',
  'just developed irritable bowel syndrome',
  'was spotted drinking appletinis at the bowling alley bar',
  'ate too much kringle today',
  'needs a sabbatical',
  'pickles their own cucumbers and never shuts up about it',
  'needs to feed Sophie her cold cuts for the day',
  'is finally going to buy those Phillips Smartbulbs after all',
  'can cook minute rice in 55 seconds',
  'got fired from the M&Ms factory for throwing away all the W\'s',
  'can kill two stones with one bird',
  'still uses Ask Jeeves',
  'volunteered to dev a one page checkout',
  'was the one who forgot the beer when we went tubing',
  'has already scheduled a Halloween party for October 2019',
  'is not really allowed to play but we\'re trying to be inclusive here',
  'is a major player down at the cracker factory',
  'puts the "laughter" in "manslaughter"',
  'drinks the bag of bacon juice when no one\'s looking',
  'is wondering when to start that pooper scooper business',
  'got the Klondike bar but now lives in constant regret',
  'is the reason why we can\'t have hummus anymore',
  'thinks we\'re all a bunch of Eurotrash',
  'ate all the skins off the fried chicken and then just left',
  'only comes to work for the beef jerky',
  'insists that we use their adult film name',
  'is getting a little too good at bar games',
  'is buying the winner a Bud Light Orange',
  'is being forced to sew gold jackets',
  'is on probation for Googling',
  'is totally not playing on a client call',
  'is wearing a bathrobe stolen from the Knight\'s Inn',
  'doesn\'t wear pants when WFH',
];


module.exports = openers;